version: 2
updates:
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: monthly
      time: '00:00'
      timezone: 'Asia/Calcutta'
    open-pull-requests-limit: 10
    labels:
      - GHA
      - Dependencies

  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: monthly
      time: '00:00'
      timezone: 'Asia/Calcutta'
    open-pull-requests-limit: 10
    labels:
      - NPM
      - Dependencies
    groups:
      wordpress-packages:
        patterns:
          - "@wordpress/*"

  - package-ecosystem: composer
    directory: '/'
    schedule:
      interval: monthly
      time: '00:00'
      timezone: 'Asia/Calcutta'
    open-pull-requests-limit: 10
    labels:
      - Composer
      - Dependencies
