<?php
/**
 * Theme assets registration.
 *
 * @package rtCamp\Theme\Elementary
 */

declare( strict_types = 1 );

namespace rtCamp\Theme\Elementary\Core;

use rtCamp\WPFramework\AssetLoader;
use rtCamp\WPFramework\Contracts\Interfaces\Registrable;
use rtCamp\WPFramework\Contracts\Interfaces\Shareable;

/**
 * Class Assets
 *
 * The theme's asset loader: extends the framework AssetLoader and registers
 * the theme's own scripts and styles on the relevant hooks. Shared so the
 * component loader registers component assets through the same instance.
 *
 * @since 1.0.0
 */
class Assets extends AssetLoader implements Registrable, Shareable {

	/**
	 * Whether Tailwind CSS is enabled for this theme.
	 *
	 * Tailwind support is opt-in. It defaults to true when
	 * src/css/frontend/tailwind.css exists (generated by GenerateTailwindThemePlugin).
	 *
	 * To force-enable or disable before the theme loads, define the constant in
	 * wp-config.php or a must-use plugin:
	 *
	 *   define( 'ELEMENTARY_THEME_ENABLE_TAILWIND', true );
	 *   define( 'ELEMENTARY_THEME_ENABLE_TAILWIND', false );
	 *
	 * To override at runtime (e.g. from a child theme or plugin):
	 *
	 *   add_filter( 'elementary_theme_tailwind_enabled', '__return_true' );
	 *   add_filter( 'elementary_theme_tailwind_enabled', '__return_false' );
	 *
	 * @var bool
	 */
	private bool $tailwind_enabled = false;

	/**
	 * Constructor.
	 */
	public function __construct() {
		parent::__construct(
			ELEMENTARY_THEME_PATH,
			get_template_directory_uri(),
			'assets/build'
		);

		$this->tailwind_enabled = (bool) apply_filters(
			'elementary_theme_tailwind_enabled',
			ELEMENTARY_THEME_ENABLE_TAILWIND
		);
	}

	/**
	 * Register hooks.
	 *
	 * @since 1.0.0
	 */
	public function register_hooks(): void {
		add_action( 'wp_enqueue_scripts', [ $this, 'register_assets' ] );
		add_action( 'wp_enqueue_scripts', [ $this, 'enqueue_assets' ] );
		add_filter( 'render_block', [ $this, 'enqueue_block_specific_assets' ], 10, 2 );
	}

	/**
	 * Register assets.
	 *
	 * @since 1.0.0
	 *
	 * @action wp_enqueue_scripts
	 */
	public function register_assets(): void {
		$this->register_script( 'core-navigation', 'js/frontend/core-navigation' );
		$this->register_style( 'core-navigation', 'css/frontend/core-navigation' );
		$this->register_style( 'elementary-theme-styles', 'css/frontend/styles' );

		if ( $this->tailwind_enabled ) {
			$this->register_style( 'elementary-theme-tailwind', 'css/frontend/tailwind' );
		}
	}

	/**
	 * Enqueue block specific assets.
	 *
	 * @param string               $markup Markup of the block.
	 * @param array<string, mixed> $block  Array with block information.
	 *
	 * @return string Updated markup.
	 *
	 * @since 1.0.0
	 *
	 * @action render_block
	 */
	public function enqueue_block_specific_assets( string $markup, array $block ): string {
		if ( ! empty( $block['blockName'] ) && 'core/navigation' === $block['blockName'] ) {
			wp_enqueue_script( 'core-navigation' );
			wp_enqueue_style( 'core-navigation' );
		}

		return $markup;
	}

	/**
	 * Enqueue JS and CSS in frontend.
	 *
	 * @since 1.0.0
	 *
	 * @action wp_enqueue_scripts
	 */
	public function enqueue_assets(): void {
		wp_enqueue_style( 'elementary-theme-styles' );

		if ( $this->tailwind_enabled ) {
			wp_enqueue_style( 'elementary-theme-tailwind' );
		}

		if ( 'local' === wp_get_environment_type() && ! ELEMENTARY_THEME_DISABLE_BROWSER_SYNC ) {
			if ( defined( 'ELEMENTARY_THEME_BROWSER_SYNC_URL' ) ) {
				$bs_url = ELEMENTARY_THEME_BROWSER_SYNC_URL;
			} else {
				$scheme = is_ssl() ? 'https' : 'http';
				$host   = wp_parse_url( home_url(), PHP_URL_HOST );
				$host   = $host ? $host : 'localhost';
				$port   = $this->get_browser_sync_port();
				$bs_url = "{$scheme}://{$host}:{$port}/browser-sync/browser-sync-client.js";
			}
			wp_enqueue_script( 'elementary-browser-sync', $bs_url, [], ELEMENTARY_THEME_VERSION, true );
		}
	}

	/**
	 * Read the BrowserSync port from .env.local (BS_PORT), defaulting to 3000.
	 *
	 * Keeps the enqueued client URL in sync with the port webpack/BrowserSync
	 * actually bind to, which is read from the same .env.local on the build side.
	 * Falls back to the default when BS_PORT is absent or not a valid TCP port
	 * (1–65535).
	 *
	 * THIS METHOD IS INTENDED FOR LOCAL DEVELOPMENT ENVIRONMENTS ONLY.
	 *
	 * @return int BrowserSync port.
	 */
	private function get_browser_sync_port(): int {
		$default  = 3000;
		$env_file = $this->base_dir . '.env.local';

		if ( ! is_readable( $env_file ) ) {
			return $default;
		}

		// phpcs:ignore WordPress.WP.AlternativeFunctions.file_get_contents_file_get_contents -- Local dev only; reading a small project file, not remote.
		$contents = file_get_contents( $env_file );

		if ( false === $contents ) {
			return $default;
		}

		if ( preg_match( '/^\s*BS_PORT\s*=\s*(\d+)/m', $contents, $matches ) ) {
			$port = (int) $matches[1];

			if ( $port >= 1 && $port <= 65535 ) {
				return $port;
			}
		}

		return $default;
	}
}
