<?php
/**
 * Theme bootstrap file.
 *
 * @package rtCamp\Theme\Elementary
 */

declare( strict_types = 1 );

namespace rtCamp\Theme\Elementary\Core;

use rtCamp\Theme\Elementary\Framework\Traits\AssetLoaderTrait;
use rtCamp\Theme\Elementary\Framework\Traits\Singleton;

/**
 * Class Assets
 *
 * @since 1.0.0
 */
class Assets {

	use AssetLoaderTrait;
	use Singleton;

	/**
	 * Whether Tailwind CSS is enabled for this theme.
	 *
	 * Tailwind support is opt-in. It defaults to true when
	 * src/css/frontend/tailwind.css exists (generated by GenerateTailwindThemePlugin).
	 *
	 * To force-enable or disable before the theme loads, define the constant in
	 * wp-config.php or a must-use plugin:
	 *
	 *   define( 'THEME_ELEMENTARY_ENABLE_TAILWIND', true );
	 *   define( 'THEME_ELEMENTARY_ENABLE_TAILWIND', false );
	 *
	 * To override at runtime (e.g. from a child theme or plugin):
	 *
	 *   add_filter( 'elementary_tailwind_enabled', '__return_true' );
	 *   add_filter( 'elementary_tailwind_enabled', '__return_false' );
	 *
	 * @var bool
	 */
	private bool $tailwind_enabled = false;

	/**
	 * Constructor.
	 */
	protected function __construct() {
		$this->tailwind_enabled = (bool) apply_filters(
			'elementary_tailwind_enabled',
			THEME_ELEMENTARY_ENABLE_TAILWIND
		);
		// Setup hooks.
		$this->setup_hooks();
	}

	/**
	 * Setup hooks.
	 *
	 * @since 1.0.0
	 */
	public function setup_hooks(): void {
		add_action( 'wp_enqueue_scripts', [ $this, 'register_assets' ] );
		add_action( 'wp_enqueue_scripts', [ $this, 'enqueue_assets' ] );
		add_filter( 'render_block', [ $this, 'enqueue_block_specific_assets' ], 10, 2 );
	}

	/**
	 * Register assets.
	 *
	 * @since 1.0.0
	 *
	 * @action wp_enqueue_scripts
	 */
	public function register_assets(): void {
		$this->register_script( 'core-navigation', 'js/frontend/core-navigation.js' );
		$this->register_style( 'core-navigation', 'css/frontend/core-navigation.css' );
		$this->register_style( 'elementary-theme-styles', 'css/frontend/styles.css' );

		if ( $this->tailwind_enabled ) {
			$this->register_style( 'elementary-theme-tailwind', 'css/frontend/tailwind.css' );
		}
	}

	/**
	 * Enqueue block specific assets.
	 *
	 * @param string               $markup Markup of the block.
	 * @param array<string, mixed> $block  Array with block information.
	 *
	 * @return string Updated markup.
	 *
	 * @since 1.0.0
	 *
	 * @action render_block
	 */
	public function enqueue_block_specific_assets( string $markup, array $block ): string {
		if ( ! empty( $block['blockName'] ) && 'core/navigation' === $block['blockName'] ) {
			wp_enqueue_script( 'core-navigation' );
			wp_enqueue_style( 'core-navigation' );
		}

		return $markup;
	}

	/**
	 * Enqueue JS and CSS in frontend.
	 *
	 * @since 1.0.0
	 *
	 * @action wp_enqueue_scripts
	 */
	public function enqueue_assets(): void {
		wp_enqueue_style( 'elementary-theme-styles' );

		if ( $this->tailwind_enabled ) {
			wp_enqueue_style( 'elementary-theme-tailwind' );
		}
	}
}
