name: 'Setup Node with Cache'
description: 'Sets up Node.js and caches node_modules'

runs:
  using: 'composite'
  steps:
    - name: Setup Node
      uses: actions/setup-node@v6.2.0
      with:
        node-version-file: '.nvmrc'

    - name: Get node version
      id: node
      run: echo "version=$(node -v)" >> $GITHUB_OUTPUT
      shell: bash

    - name: Cache node_modules
      id: node_modules
      uses: actions/cache@v5.0.3
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json', '**/.npmrc') }}-${{ steps.node.outputs.version }}

    - name: Install Node dependencies
      if: steps.node_modules.outputs.cache-hit != 'true'
      run: npm ci --ignore-scripts
      shell: bash
      env:
        CI: true
