name: Test and Measure

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - ready_for_review

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  pre-run:
    name: 'Pre run'
    runs-on: ubuntu-latest
    outputs:
      changed-css-count: ${{ steps.determine-file-counts.outputs.css-count }}
      changed-js-count: ${{ steps.determine-file-counts.outputs.js-count }}
      changed-php-count: ${{ steps.determine-file-counts.outputs.php-count }}

    steps:
      - name: Checkout including last 2 commits
        # Fetch last 2 commits if it's not a PR, so that we can determine the list of modified files.
        if: ${{ github.base_ref == null }}
        uses: actions/checkout@v6
        with:
          fetch-depth: 2

      - name: Checkout
        # Do usual checkout if it's a PR.
        if: ${{ github.base_ref != null }}
        uses: actions/checkout@v6

      - name: Fetch base branch
        # Only fetch base ref if it's a PR.
        if: ${{ github.base_ref != null }}
        run: git fetch --depth=1 --no-tags origin ${{ github.base_ref }}

      - name: Determine modified files for PR
        if: ${{ github.base_ref != null }}
        run: echo "MODIFIED_FILES=$(git diff --name-only FETCH_HEAD HEAD | base64 -w 0)" >> $GITHUB_ENV

      - name: Determine modified files for commit
        if: ${{ github.base_ref == null }}
        run: echo "MODIFIED_FILES=$(git diff --name-only HEAD~1 HEAD | base64 -w 0)" >> $GITHUB_ENV

      - id: determine-file-counts
        name: Determine if modified files should make the workflow run continue
        run: |
          MODIFIED_FILES=$(echo "$MODIFIED_FILES" | base64 -d)
          echo -e "Modified files:\n$MODIFIED_FILES\n"

          MODIFIED_FILES_DATA=$(node .github/bin/determine-modified-files-count.js "$IGNORE_PATH_REGEX" "$MODIFIED_FILES" "all")
          CSS_FILE_COUNT=$(node .github/bin/determine-modified-files-count.js ".+\.s?css|package\.json|package-lock\.json" "$MODIFIED_FILES")
          JS_FILE_COUNT=$(node .github/bin/determine-modified-files-count.js ".+\.(js|snap)|package\.json|package-lock\.json" "$MODIFIED_FILES")
          PHP_FILE_COUNT=$(node .github/bin/determine-modified-files-count.js ".+\.php|composer\.(json|lock)|phpstan\.neon\.dist" "$MODIFIED_FILES")
          GHA_WORKFLOW_COUNT=$(node .github/bin/determine-modified-files-count.js "(\.github\/(workflows|actions)\/.+\.yml)" "$MODIFIED_FILES")

          echo "Changed file count: $MODIFIED_FILES_DATA"
          echo "Changed ${{ github.event.repository.name }} CSS file count: $CSS_FILE_COUNT"
          echo "Changed ${{ github.event.repository.name }} JS file count: $JS_FILE_COUNT"
          echo "Changed ${{ github.event.repository.name }} PHP file count: $PHP_FILE_COUNT"
          echo "Changed GHA workflow/actions count: $GHA_WORKFLOW_COUNT"

          echo "css-count=$CSS_FILE_COUNT" >> $GITHUB_OUTPUT
          echo "js-count=$JS_FILE_COUNT" >> $GITHUB_OUTPUT
          echo "php-count=$PHP_FILE_COUNT" >> $GITHUB_OUTPUT
        env:
          # Ignore Paths:
          # - .github/
          # - !.github/workflows
          # - !.github/actions
          # - .wordpress-org/
          # - docs/
          IGNORE_PATH_REGEX: \.github\/(?!workflows)(?!actions)|\.wordpress-org\/|docs\/

      - name: Summarize skipped jobs
        run: |
          SKIPPED=()

          [[ "${{ steps.determine-file-counts.outputs.css-count }}" -le 0 ]] && SKIPPED+=("lint-css")
          [[ "${{ steps.determine-file-counts.outputs.js-count }}" -le 0 ]] && SKIPPED+=("lint-js" "unit-tests-js" "build-prod")
          [[ "${{ steps.determine-file-counts.outputs.php-count }}" -le 0 ]] && SKIPPED+=("lint-php" "unit-test-php")

          if [[ ${#SKIPPED[@]} -gt 0 ]]; then
            echo "The following jobs will be skipped as no relevant files were changed:"
            for JOB in "${SKIPPED[@]}"; do
              echo "  - $JOB"
            done
          else
            echo "All jobs will run."
          fi

  lint-css:
    needs: pre-run
    if: needs.pre-run.outputs.changed-css-count > 0
    name: 'Lint CSS'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node with cache
        uses: ./.github/actions/setup-node-with-cache

      - name: Detect coding standard violations (stylelint)
        run: npm run lint:css

  lint-js:
    needs: pre-run
    if: needs.pre-run.outputs.changed-js-count > 0
    name: 'Lint JS'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node with cache
        uses: ./.github/actions/setup-node-with-cache

      - name: Detect coding standard violations (eslint)
        run: npm run lint:js

  unit-tests-js:
    needs: pre-run
    if: needs.pre-run.outputs.changed-js-count > 0
    name: 'Run JS unit tests'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node with cache
        uses: ./.github/actions/setup-node-with-cache

      - name: Run unit tests
        run: npm run test:js
        env:
          CI: true

  lint-php:
    needs: pre-run
    if: needs.pre-run.outputs.changed-php-count > 0
    name: 'Lint PHP'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: none
          tools: cs2pr

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Configure Composer cache
        uses: actions/cache@v5.0.3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: composer install --prefer-dist --optimize-autoloader --no-progress --no-interaction --no-scripts

      - name: Validate composer.json
        run: composer --no-interaction validate --no-check-all

      - name: Detect coding standard violations (PHPCS)
        run: vendor/bin/phpcs -q --report=checkstyle --runtime-set ignore_errors_on_exit 1 --runtime-set ignore_warnings_on_exit 1 | cs2pr --graceful-warnings

  unit-test-php:
    needs: pre-run
    if: needs.pre-run.outputs.changed-php-count > 0
    name: "PHP Unit test"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node with cache
        uses: ./.github/actions/setup-node-with-cache

      - name: Start WP environment
        run: npm run wp-env start

      - name: Run tests
        run: npm run test:php

  build-prod:
    needs: pre-run
    if: needs.pre-run.outputs.changed-js-count > 0 || needs.pre-run.outputs.changed-css-count > 0
    name: 'Build production'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node with cache
        uses: ./.github/actions/setup-node-with-cache

      - name: Build production
        id: build
        run: npm run build:prod
        env:
          CI: true